name: graph-update

on: deployment_status

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  update-graph:
    name: Update Apollo Graph
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_URL: ${{ github.event.deployment_status.target_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Apollo client
        run: echo $DEPLOYMENT_URL
      - run: echo ${GITHUB_REF##*/}
