name: graph-update

on: deployment_status

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  update-graph:
    name: Update Apollo Graph
    runs-on: ubuntu-latest
    if: github.event.deployment_status.status == 'success'
    env:
      SERVICE_NAME: media
      GRAPH_ENDPOINT: ${{ github.event.deployment_status.target_url }}/api/graphql
      GRAPH: climbingzone-graph
      GATEWAY_PROJECT: vercel
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get deployment environment
        id: deployment_environment
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.event.deployment.environment }}
      - name: Echo Deployment URL
        run: echo $DEPLOYMENT_URL
      - name: Echo Service
        run: echo $(echo ${GRAPH_ENDPOINT:8} | cut -d'-' -f 1)
      - name: Echo graph variant
        id: graph_variant
        run: echo ${{ steps.deployment_environment.outputs.lowercase }}
      - name: Service conditional
        run: if [  "$(echo ${GRAPH_ENDPOINT:8} | cut -d'-' -f 1)" = "$GATEWAY_PROJECT"  ];then echo "BOO"; fi
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install Apollo CLI
        run: yarn add apollo@^2.30.3 -W
      - name: Update Apollo Studio Graph
        run: |
          if [ "$(echo ${GRAPH_ENDPOINT:8} | cut -d'-' -f 1)" = "$GATEWAY_PROJECT" ]; then
              echo "Gateway does not require graph update"
          else
            yarn apollo service:push \
            --graph=$GRAPH \
            --variant=${{ steps.deployment_environment.outputs.lowercase }} \
            --endpoint=$GRAPH_ENDPOINT \
            --serviceName=$(echo ${GRAPH_ENDPOINT:8} | cut -d'-' -f 1) \
            --serviceURL=$GRAPH_ENDPOINT \
            --key=${{ secrets.APOLLO_KEY }}
          fi
