name: graph-update

on: deployment_status

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  update-graph:
    name: Update Apollo Graph
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_URL: ${{ github.event.deployment_status.target_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Install Apollo client
        run: echo $DEPLOYMENT_URL
      - run: echo ${BRANCH_NAME}
