name: graph-update

on: deployment_status

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  update-graph:
    name: Update Apollo Graph
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: "media"
      DEPLOYMENT_URL: ${{ github.event.deployment_status.target_url }}/api/graphql

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get deployment environment
        id: deployment_environment
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.event.deployment.environment }}
      - name: Echo Deployment URL
        run: echo $DEPLOYMENT_URL
      - name: Echo graph variant
        id: graph_variant
        run: echo ${{ steps.deployment_environment.outputs.lowercase }}
      - name: Install Apollo CLI
        run: yarn add apollo@^2.30.3
      - name: Update Apollo Studio Graph
        run: yarn apollo service:push --endpoint=$DEPLOYMENT_URL --serviceName=$SERVICE_NAME --serviceURL=$DEPLOYMENT_URL
